[mypy]
python_version = 3.13
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
strict_optional = True

namespace_packages = True
explicit_package_bases = True

ignore_missing_imports = True

[mypy-wattnet.*]
disallow_untyped_defs = True
