[tool.poetry]
name = "wattnet-api"
version = "1.0.0"
description = "REST API for wattnet"
authors = ["Jaime Iglesias Blanco <iglesias@ifca.unican.es>"]
readme = "README.md"
homepage = "https://wattnet.eu"
repository = "https://github.com/wattnet/wattnet-api"
documentation = "https://api.wattnet.eu/docs"
packages = [{ include = "wattnet" }]
include = ["config/.env.example"]

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
fastapi = "0.121.1"
uvicorn = "0.38.0"
requests = "^2.33.0"
fastapi-versioning = "0.10.0"
geopandas = "1.1.2"
pydantic = "2.12.4"
shapely = "2.1.2"
trio = "0.32.0"
pydantic-settings = "^2.12.0"
typing-extensions = "4.15.0"
wattnet-storage = { git = "ssh://git@github.com/wattnet/wattnet-storage.git" }

[tool.poetry.scripts]
wattnet-api = "wattnet.api.app:main"

[tool.poetry.group.test.dependencies]
pytest = "^8.0"
pytest-trio = "^0.8.0"
pytest-cov = "^7.0.0"

[tool.poetry.group.dev.dependencies]
tox = "4.16.0"

[tool.poetry.group.lint.dependencies]
flake8 = ">=4,<8"
flake8-bugbear = ">=22.3,<26.0"
flake8-docstrings = "^1.6"
flake8-typing-imports = "^1.12"
flake8-colors = "^0.1"
pep8-naming = ">=0.12,<0.16"
pydocstyle = "^6.1"

[tool.poetry.group.format.dependencies]
black = ">=22.3,<27.0"

[tool.poetry.group.security.dependencies]
bandit = "1.9.3"

[tool.poetry.group.types.dependencies]
mypy = "1.19.1"
types-requests = "^2.31.0"

[tool.poetry.group.release.dependencies]
twine = ">=4.0.2,<7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
