[tox]
min_version = 4.3.3
isolated_build = true
skipsdist = true
envlist =
    py3{8,9,10,11,12,13}
    flake8
    black
    bandit
    mypy
    pypi

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, flake8, black, bandit, mypy, pypi

[base]
python = python3.13
package = wattnet.api
src_path = wattnet

[testenv]
usedevelop = true
basepython = python3
allowlist_externals =
    poetry
    find
    rm
    mkdir
setenv =
    VIRTUAL_ENV={envdir}
    LC_ALL=en_US.utf-8
commands_pre =
    poetry -V
    poetry sync --no-root
commands =
    find . -type f -name "*.pyc" -delete

[testenv:py38]
basepython = python3.8

[testenv:py39]
basepython = python3.9

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13

[flake8]
max-line-length = 88
show-source = true
builtins = _
exclude =
    .venv
    .git
    .tox
    dist
    docs
    build
    *lib/python*
    *egg

[testenv:flake8]
basepython = {[base]python}
commands =
    poetry run flake8 {[base]src_path}

[testenv:black]
basepython = {[base]python}
commands =
    poetry run black --check --diff {[base]src_path}

[testenv:bandit]
basepython = {[base]python}
commands =
    poetry run bandit -r {[base]src_path} -s B110,B410

[testenv:mypy]
description = Static type checks
basepython = {[base]python}
commands =
    poetry run mypy \
        --config-file mypy.ini \
        -p {[base]package} \
        --explicit-package-bases

[testenv:pypi]
description = Dry-run PyPI publish
basepython = {[base]python}
commands =
    poetry publish --build --dry-run
